export const GET_TODOS = 'GET_TODOS'
export const GET_TODO = 'GET_TODO'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'
export const REGISTER_USER = 'REGISTER_USER'
